### PR TITLE
New section: Flags

### PR DESCRIPTION
**Pull request by d2dyno**
Added new section with all flags. Also change FAQ to linkable type.

### CODE REVIEW

**Comment by d2dyno** [comment]
Sorry for all the commit spam - I am learning RST lol

**Comment by JohnDoee** [comment]
Just give a heads-up when you think it's good :+1:.

**Comment by d2dyno** [comment]
@JohnDoee it should be ready to go, just had to resolve a conflict from your latest change.

**Comment by JohnDoee** [comment]
Thanks!

**Pull request merged**
